### PR TITLE
Modify README and LICENSE, add third-party-programs.txt file

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
2 @yssemaev: Yuri, could you review this PR?

**Comment by LeonidBeynenson** [comment]
2 @evgeny-izutov : Evgeny, I changed a bit README file. Please, take a look.

**Comment by evgeny-izutov** [comment]
@LeonidBeynenson, for me it's ok.

**Review by yssemaev — COMMENTED** [review]
Looks ok.

**Review by evgeny-izutov — APPROVED** [review]

**Pull request merged**
